services:
  app:
    build: .
    container_name: fastapi-docker-with-uv-container
    command: uv run uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
    volumes:
      - .:/app